### ISSUE TITLE
New datasheet and shorter algorithm

### ISSUE THREAD

**Issue by gewoods3** [sparkfun/Barometric_Pressure_Sensor_Breakout-MPL115A1#1]
A more recent datasheet is here: [MPL115A1](https://www.nxp.com/docs/en/data-sheet/MPL115A1.pdf). 
A related application note is here: [How to Implement the Freescale MPL115A Digital Barometer](https://www.nxp.com/docs/en/application-note/AN3785.pdf).
A shorter version of the conversion algorithm is in the application note. See **Coding Section**, `calculatePCompShort`.

**Comment by nseidle** [comment]
Thanks! We're no longer actively working on this product but we'll leave this issue open so other folks can find it.
